# Generated by Django 4.0.6 on 2022-07-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
