# Generated by Django 5.2.9 on 2025-12-30 10:34

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0007_alter_userprogress_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=(datetime.now())),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='time_taken',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
