# Generated by Django 5.2.9 on 2025-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
