# Generated by Django 5.2.9 on 2025-12-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_answer',
            new_name='answer',
        ),
    ]
