# Generated by Django 5.2.9 on 2025-12-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0004_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
