# Generated by Django 5.2.9 on 2025-12-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0005_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_at_client',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_at_server',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
