# Generated by Django 5.2.9 on 2025-12-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0006_remove_answer_answered_at_answer_answered_at_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='time_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
