# Generated by Django 5.2.9 on 2025-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0008_userprogress_date_alter_userprogress_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
