# Generated by Django 5.2.9 on 2025-12-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0009_alter_userprogress_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_at_server',
            field=models.DateTimeField(null=True),
        ),
    ]
