# Generated by Django 4.1.7 on 2023-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="extra",
        ),
        migrations.AddField(
            model_name="score",
            name="extras",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
