# Generated by Django 4.1.7 on 2023-05-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0003_remove_score_extras_score_extra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessons",
            old_name="group",
            new_name="groups",
        ),
    ]
