# Generated by Django 4.1.7 on 2023-05-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0004_rename_group_lessons_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lessons",
            old_name="groups",
            new_name="group",
        ),
    ]
