# Generated by Django 4.1.7 on 2023-05-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0005_rename_groups_lessons_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessons",
            name="alt_teacher",
        ),
        migrations.RemoveField(
            model_name="lessons",
            name="group",
        ),
        migrations.RemoveField(
            model_name="lessons",
            name="teacher",
        ),
        migrations.AddField(
            model_name="schedule",
            name="alt_teacher",
            field=models.ManyToManyField(
                related_name="alt_teacher", to="classbook.teachers"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="classbook.classes",
                verbose_name="Класс",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="teacher",
            field=models.ManyToManyField(
                related_name="prime_teacher", to="classbook.teachers"
            ),
        ),
    ]
