# Generated by Django 4.1.7 on 2023-05-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0006_remove_lessons_alt_teacher_remove_lessons_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="classbook.classes",
                verbose_name="Класс",
            ),
            preserve_default=False,
        ),
    ]
