# Generated by Django 4.1.7 on 2023-05-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0007_lessons_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLessons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.SmallIntegerField()),
                ("variant", models.SmallIntegerField()),
                ("lesson_time", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="number",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="classbook.timelessons",
            ),
            preserve_default=False,
        ),
    ]
