# Generated by Django 4.1.7 on 2023-05-22 12:18
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0008_timelessons_schedule_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelessons",
            name="rest_length",
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
    ]
