# Generated by Django 4.1.7 on 2023-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0009_timelessons_rest_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="alt_teacher",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="alt_teacher",
                to="classbook.teachers",
            ),
        ),
    ]
