# Generated by Django 4.1.7 on 2023-05-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0011_alter_schedule_alt_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
