# Generated by Django 4.1.7 on 2023-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0012_schedule_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="date",
        ),
        migrations.AddField(
            model_name="schedule",
            name="day",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
