# Generated by Django 4.1.7 on 2023-05-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0013_remove_schedule_date_schedule_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="alt_teacher",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="teacher",
        ),
        migrations.AddField(
            model_name="schedule",
            name="alt_teacher",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alt_teacher",
                to="classbook.teachers",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prime_teacher",
                to="classbook.teachers",
            ),
            preserve_default=False,
        ),
    ]
