# Generated by Django 4.1.7 on 2023-05-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "classbook",
            "0014_remove_schedule_alt_teacher_remove_schedule_teacher_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="alt_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alt_teacher",
                to="classbook.teachers",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="cabinet",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="extra_info",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
