# Generated by Django 4.1.7 on 2023-05-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "classbook",
            "0015_alter_schedule_alt_teacher_alter_schedule_cabinet_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessons",
            name="discipline",
        ),
        migrations.AddField(
            model_name="lessons",
            name="discipline",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="classbook.disciplines",
            ),
            preserve_default=False,
        ),
    ]
