# Generated by Django 4.1.7 on 2023-05-31 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0016_remove_lessons_discipline_lessons_discipline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="lesson",
        ),
        migrations.AddField(
            model_name="schedule",
            name="discipline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="classbook.disciplines",
            ),
        ),
    ]
