# Generated by Django 4.1.7 on 2023-06-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0017_remove_schedule_lesson_schedule_discipline"),
    ]

    operations = [
        migrations.AddField(
            model_name="pupils",
            name="sub_group",
            field=models.SmallIntegerField(default=1),
        ),
    ]
