# Generated by Django 4.1.7 on 2023-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0018_pupils_sub_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="sub_group",
            field=models.SmallIntegerField(default=1),
        ),
    ]
