# Generated by Django 4.1.7 on 2023-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0019_schedule_sub_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
