# Generated by Django 4.1.7 on 2023-06-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0020_lessons_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="teacher",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="classbook.teachers",
            ),
            preserve_default=False,
        ),
    ]
