# Generated by Django 4.1.7 on 2023-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0021_lessons_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons",
            name="number",
            field=models.SmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
