# Generated by Django 4.1.7 on 2023-06-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0022_lessons_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.CharField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "н")],
                max_length=25,
                verbose_name="Оценка",
            ),
        ),
    ]
