# Generated by Django 4.1.7 on 2023-07-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0024_score_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="deleted",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teachers",
            name="can_teach",
            field=models.ManyToManyField(
                to="classbook.disciplines", verbose_name="Может преподавать:"
            ),
        ),
    ]
