# Generated by Django 4.1.7 on 2023-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0025_score_deleted_alter_teachers_can_teach"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="deleted",
            field=models.BooleanField(default=0),
        ),
    ]
