# Generated by Django 4.1.7 on 2023-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classbook", "0026_alter_score_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="sub_group",
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
