# Generated by Django 5.2.9 on 2025-12-10 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbook', '0027_alter_schedule_sub_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktp',
            name='klass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='classbook.classes', verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
