# Generated by Django 5.2.9 on 2025-12-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classbook', '0028_ktp_klass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание'},
        ),
    ]
